project:
  type: website
  output-dir: docs

website:
  title: "Isabella Segarra"
  #favicon: photo-of-me.png
  navbar:
    #logo:images/logo.png
    #logo-alt:
    #title:false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd
      - posts.qmd
      - href: resources.qmd
        text: Resources
      - icon: github 
        href: https://github.com/IsabellaSegarra/IsabellaSegarra.github.io
    page-footer: 
      left: Copyright 2025, Isabella Segarra 
      right: something here

format:
  html:
    theme: styles.scss
    toc: true
    page-layout: full
    mainfont: Josefin Sans 

editor: visual

